### ISSUE TITLE
Parse error when using the squiggly heredoc

### ISSUE THREAD

**Issue by NicolasWebDev** [seattlerb/debride#37] opened 2017-07-04 20:13 UTC
debride gives a parsing error when encountering this block:
```ruby
def credentials
  query = <<~END
    SELECT e.*
    FROM empresa;
  END
end
```

```
Parse Error parsing invoice_downloader.rb. Skipping.                                                 
  invoice_downloader.rb:51 :: parse error on value "<<" (tLSHFT)                                     
```

**Comment by phiggins** [comment] 2017-07-08 22:02
This is most likely due to seattlerb/ruby_parser#218. That issue has been fixed on master, so this problem should go away with the next release of ruby_parser.

**Comment by NicolasWebDev** [comment] 2017-07-10 14:56
Thanks, you are right.

**Comment by phiggins** [comment] 2017-07-18 20:49
@NicolasWebDev A new version of ruby_parser was released yesterday. Did that fix your issue?

**Comment by NicolasWebDev** [comment] 2017-07-18 22:28
With the following code
```ruby
puts <<~END
  chien
  chat
  poulet
END
```
, I now have the error

```
+ ~/tmp/test_debride$ debride test.rb                        
Parse Error parsing test.rb. Skipping.                       
  test.rb:1 :: parse error on value ["END", 1] (klEND)
These methods MIGHT not be called:
```

```
+ ~/tmp/test_debride$ cat Gemfile.lock                       
GEM                                                          
  remote: https://rubygems.org/
  specs:
    debride (1.8.0)
      path_expander (~> 1.0)
      ruby_parser (~> 3.6)
      sexp_processor (~> 4.5)
    path_expander (1.0.2)
    ruby_parser (3.10.0)
      sexp_processor (~> 4.9)
    sexp_processor (4.10.0)

PLATFORMS
  ruby

DEPENDENCIES
  debride

BUNDLED WITH
   1.15.1
```

**Comment by phiggins** [comment] 2017-07-19 03:22
Hi, I don't see that error message with a newly installed debride. Do you get different output when you run this command?

```
pete@rhombus:~/projects/test_debride2$ gem list debride ruby_parser sexp_processor

*** LOCAL GEMS ***

debride (1.8.0)

*** LOCAL GEMS ***

ruby_parser (3.10.0)

*** LOCAL GEMS ***

sexp_processor (4.10.0)
```

What version of ruby are you using?

**Comment by NicolasWebDev** [comment] 2017-07-19 05:23
```
+ ~/tmp/test_debride$ gem list debride ruby_parser sexp_processor

*** LOCAL GEMS ***     

debride (1.8.0)        

*** LOCAL GEMS ***     

ruby_parser (3.10.0, 3.9.0)                    

*** LOCAL GEMS ***     

sexp_processor (4.10.0, 4.9.0)                 
```

I am running debride with bundle exec, with the Gemfile.lock above, so it should use ruby_parser 3.10.0 and sexp_processor 4.10.0, isn't it? I am managing my gems/ruby versions with rbenv.

I am using ruby 2.4.1.

**Comment by zenspider** [comment] 2017-07-20 22:35
This is legit and I can reproduce it in ruby_parser. :(

**Comment by zenspider** [comment] 2017-07-21 00:04
Fixed. It was my fault and dumb. Still need better test structure to prevent regressions.

**Closed by zenspider** 2017-07-21 00:05 UTC

**Comment by zenspider** [comment] 2017-07-21 08:13
released

**Comment by NicolasWebDev** [comment] 2017-07-22 00:30
Thanks @zenspider.
